version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  telecom:
    image: ksashoeb/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=testNG.xml
    volumes:
      - ./telecom-result1:/usr/share/ksa/test-output
  telecomff:
    image: ksashoeb/docker-selenium
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=testNG.xml
    volumes:
      - ./telecom-result2:/usr/share/ksa/test-output